apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  application.yml: |-
    bpms.url: http://bpms:8080
    dso.url: http://digital-signature-ops:8080
    spring.zipkin.baseUrl: http://zipkin.istio-system:9411
    form-submission-validation.url: http://form-submission-validation:8080
    server.max-http-header-size: 32KB
    {{- if eq .Values.deployProfile "dev" }}
    management.endpoints.web.exposure.include: '*'
    {{- else }}
    management.endpoints.web.exposure.include: 'health, prometheus'
    {{- end }}
    redis.endpoint : rfs-redis-sentinel.{{ .Release.Namespace }}.svc:26379
    storage: {{ toYaml .Values.storage | nindent 6 }}
    platform.security.csrf.enabled: {{ .Values.platform.security.csrf.enabled }}